version: '3.8'

services:
  ipsecai-ui:
    build: .
    container_name: ipsecai-ui
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://ipsecai-api:8000
    command: streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - ipsecai-api

  ipsecai-api:
    build: .
    container_name: ipsecai-api
    ports:
      - "8000:8000"
    command: uvicorn backend.api:app --host 0.0.0.0 --port 8000
