"""
IPsecAI Testbed Configuration Generator
Generates reproducible IPsec VPN test profiles, expected security outcomes, and strongSwan / swanctl configuration templates.
"""

from typing import Dict, Any
from datetime import datetime
import uuid

from backend.models.schema import TestbedRequest, TestbedProfile, SecurityAssociation, IPsecSession
from backend.assessment.rule_engine import RuleEngine
from backend.assessment.scoring_engine import ScoringEngine


class TestbedGenerator:
    def __init__(self):
        self.rule_engine = RuleEngine()
        self.scoring_engine = ScoringEngine()

    def generate_test_profile(self, req: TestbedRequest) -> TestbedProfile:
        profile_id = f"TB-{str(uuid.uuid4())[:8].upper()}"
        
        # Build mock session to evaluate expected score
        sa = SecurityAssociation(
            spi_in="0x12345678",
            spi_out="0x87654321",
            protocol="ESP",
            mode=req.vpn_mode,
            encryption_algorithm=req.encryption_algorithm,
            integrity_algorithm="AEAD (Built-in)" if "GCM" in req.encryption_algorithm else "HMAC-SHA256",
            dh_group=req.dh_group,
            pfs_enabled=req.pfs_enabled,
            replay_protection_enabled=req.replay_protection,
            replay_window_size=64 if req.replay_protection else 0,
            sa_lifetime_seconds=req.lifetime_hours * 3600,
            sa_volume_limit_mb=4096,
            metadata_padding_enabled=False,
            ip_version=req.ip_version
        )

        session = IPsecSession(
            session_id=profile_id,
            src_endpoint="198.51.100.10" if req.ip_version == "IPv4" else "2001:db8:1::10",
            dst_endpoint="203.0.113.20" if req.ip_version == "IPv4" else "2001:db8:2::20",
            vpn_mode=req.vpn_mode,
            ipsec_protocol="ESP",
            ike_version="IKEv2",
            security_association=sa,
            total_packets=1000,
            total_bytes=1000000,
            duration_seconds=60.0
        )

        findings = self.rule_engine.evaluate_session(session)
        assessment = self.scoring_engine.assess(session, findings)

        # Traffic flow characteristics profile
        traffic_profiles = {
            "Video": {"packet_rate": "80-150 pkt/s", "avg_size": "1300 bytes", "burstiness": "High", "bandwidth": "~1.2 Mbps"},
            "VoIP": {"packet_rate": "50 pkt/s", "avg_size": "180 bytes", "burstiness": "Very Low", "bandwidth": "~72 kbps"},
            "Web Browsing": {"packet_rate": "15-40 pkt/s", "avg_size": "750 bytes", "burstiness": "Medium", "bandwidth": "~250 kbps"},
            "Email": {"packet_rate": "5-15 pkt/s", "avg_size": "550 bytes", "burstiness": "Low", "bandwidth": "~60 kbps"},
            "Messaging": {"packet_rate": "1-5 pkt/s", "avg_size": "280 bytes", "burstiness": "Low", "bandwidth": "~10 kbps"},
            "ICMP": {"packet_rate": "1 pkt/s", "avg_size": "84 bytes", "burstiness": "None", "bandwidth": "~1 kbps"}
        }

        # Map strongSwan cipher strings
        ike_prop = "aes256gcm16-prfsha256-modp2048"
        esp_prop = "aes256gcm16"
        if "CBC" in req.encryption_algorithm:
            ike_prop = "aes128-sha256-modp1024"
            esp_prop = "aes128-sha256"
        elif "3DES" in req.encryption_algorithm:
            ike_prop = "3des-sha1-modp1024"
            esp_prop = "3des-sha1"

        dh_suffix = ""
        if req.pfs_enabled:
            dh_map = {"Group 14": "-modp2048", "Group 19": "-ecp256", "Group 20": "-ecp384", "Group 2": "-modp1024"}
            dh_suffix = dh_map.get(req.dh_group, "-modp2048")
            esp_prop += dh_suffix

        # Generate strongSwan / ipsec.conf template
        strongswan_conf = f"""# strongSwan ipsec.conf Template - Generated by IPsecAI Testbed Configurator
# Test Case ID: {profile_id}
# Warning: Prototype configuration template for authorized lab use.

config setup
    charondebug="ike 2, knl 2, cfg 2, esp 2"

conn {profile_id.lower()}
    type={req.vpn_mode.lower()}
    left=198.51.100.10
    leftid=@gw1.testbed.local
    leftsubnet=10.10.0.0/24
    right=203.0.113.20
    rightid=@gw2.testbed.local
    rightsubnet=10.20.0.0/24
    ike={ike_prop}!
    esp={esp_prop}!
    keyexchange=ikev2
    ikelifetime=24h
    lifetime={req.lifetime_hours}h
    dpdaction=restart
    dpddelay=30s
    auto=start
    replay_window={'64' if req.replay_protection else '0'}
"""

        # Generate modern swanctl.conf template
        swanctl_conf = f"""# swanctl.conf Template - Generated by IPsecAI Testbed Configurator
# Test Case ID: {profile_id}

connections {{
    {profile_id.lower()} {{
        version = 2
        local_addrs = 198.51.100.10
        remote_addrs = 203.0.113.20
        proposals = {ike_prop}

        local {{
            auth = pubkey
            id = gw1.testbed.local
        }}
        remote {{
            auth = pubkey
            id = gw2.testbed.local
        }}

        children {{
            net {{
                mode = {req.vpn_mode.lower()}
                local_ts = 10.10.0.0/24
                remote_ts = 10.20.0.0/24
                esp_proposals = {esp_prop}
                lifetime = {req.lifetime_hours * 3600}s
                anti_replay = {'64' if req.replay_protection else '0'}
            }}
        }}
    }}
}}
"""

        return TestbedProfile(
            profile_id=profile_id,
            generated_at=datetime.utcnow().isoformat(),
            parameters=req,
            expected_security_score=assessment.overall_score,
            expected_risk_level=assessment.risk_level,
            expected_findings_count=len(findings),
            traffic_characteristics=traffic_profiles.get(req.traffic_type, {}),
            strongswan_conf=strongswan_conf,
            swanctl_conf=swanctl_conf,
            disclaimer="Prototype configuration template for authorized lab and testing testbeds."
        )
